version: "3.3"

services:

  telegram-bot:
    build:
      context: .
    container_name: cryptoparser-bot
    command: sh -c "cd /usr/src/telegram-bot && python -m app"
    restart: always
    volumes:
      - .:/usr/src/telegram-bot
    depends_on:
      - redis

  parser:
    build:
      context: .
    container_name: cryptoparser-parser
    command: sh -c "cd /usr/src/telegram-bot && python -m parser"
    restart: always
    volumes:
      - .:/usr/src/telegram-bot
    depends_on:
      - redis
      - telegram-bot

  redis:
    image: redis:alpine
    container_name: cryptoparser-redis
    restart: always
    volumes:
      - ./redis/data/:/data
